## Creating a logistic regression to predict absenteeism

### Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

### Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the Week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         1                2            7   
3         1         0         0         0                3            7   
4         0         0         0         1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Day of the Week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         1                2            7   
3         1         0         0         0                3            7   
4         0         0         0         1                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### A comment on the targets

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Daily Work Load Average','Distance to Work','Education','Day of the Week'], axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Children  Pets  \
0                     289   33               30         2     1   
1                     118   50               31         1     0   
2                     179   38               31         0     0   
3                     279   39               24         2     0   
4                     289   33               30         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 11)

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Standardize the data

In [15]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Pets'], dtype=object)

In [18]:
#columns_to_scale = ['Day of the Week','Month Value', 'Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index', 'Education', 'Children', 'Pets']

columns_to_omit = ['Reason_1','Reason_2','Reason_3','Reason_4']

In [19]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [20]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\itkma\anaconda3\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [21]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\itkma\anaconda3\lib\site-packages\sklearn\base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [22]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [23]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Children      Pets  
0                  1.005844 -0.536062         0.767431  0.880469  0.268487  
1                 -1.574681  2.130803         1.002633 -0.019280 -0.589690  
2                 -0.654143  0.248310         1.002633 -0.919030 -0.589690  
3                  0.854936  0.405184        -0.643782  0.880469 -0.589690  
4                  1.005844 -0.536062         0.767431  0.880469  0.268487  
..                      ...       ...              ...       ...       ...  
695               -0.654143  0.562059        -1.114186  0.880469 -0.589690  
696                0.040034 -1.320435        -0.643782 -0.019280  1.126663  
697                1.624567 -1.320435        -0.408580 -0.919030 -0.589690  
698                0.190942 -0.692937        -0.408580 -0.919030 -0.589690  
699                1.036026  0.562059        -0.408580 -0.019280  0.268487  

[700 rows x 10 columns]

In [24]:
scaled_inputs.shape

(700, 10)

### Split the data into train & test and shuffle

#### Import the relevant module

In [25]:
from sklearn.model_selection import train_test_split

#### Split

In [26]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 417         0         0         0         1    -0.673803   
 24          0         0         1         0     0.468236   
 506         0         0         0         1     0.753746   
 37          1         0         0         0     0.468236   
 645         0         0         0         1    -0.959313   
 ..        ...       ...       ...       ...          ...   
 120         0         0         0         1    -1.530333   
 131         0         0         0         1    -1.530333   
 292         0         0         0         1     1.039256   
 332         1         0         0         0     1.324766   
 288         1         0         0         0     0.753746   
 
      Transportation Expense       Age  Body Mass Index  Children      Pets  
 417                1.624567 -1.320435        -0.408580 -0.919030 -0.589690  
 24                 1.005844 -0.536062         0.767431  0.880469  0.268487  
 506                2.092381 -1.

In [27]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [28]:
print(x_train.shape, y_train.shape)

(560, 10) (560,)


In [29]:
print(x_test.shape, y_test.shape)

(140, 10) (140,)


### Logistic regression with sklearn

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model

In [31]:
reg = LogisticRegression()

In [32]:
reg.fit(x_train, y_train)

LogisticRegression()

In [33]:
reg.score(x_train, y_train)

0.7785714285714286


### Manually check the accuracy

In [34]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [36]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [37]:
np.sum((model_outputs == y_train))

436

In [38]:
model_outputs.shape[0]

560

In [39]:
np.sum((model_outputs == y_train))/model_outputs.shape[0]

0.7785714285714286

### Finding the intercept and coefficients

In [40]:
reg.intercept_

array([-1.69039985])

In [41]:
reg.coef_

array([[ 2.79972054,  0.91281646,  3.09130121,  0.85354339,  0.16419285,
         0.60132311, -0.167107  ,  0.30788685,  0.36465405, -0.26975535]])

In [42]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Children',
       'Pets'], dtype=object)

In [43]:
feature_name = unscaled_inputs.columns.values

In [44]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)
                             
summary_table

Feature Name  Coefficient
0                Reason_1     2.799721
1                Reason_2     0.912816
2                Reason_3     3.091301
3                Reason_4     0.853543
4             Month Value     0.164193
5  Transportation Expense     0.601323
6                     Age    -0.167107
7         Body Mass Index     0.307887
8                Children     0.364654
9                    Pets    -0.269755

In [45]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                Intercept    -1.690400
1                 Reason_1     2.799721
2                 Reason_2     0.912816
3                 Reason_3     3.091301
4                 Reason_4     0.853543
5              Month Value     0.164193
6   Transportation Expense     0.601323
7                      Age    -0.167107
8          Body Mass Index     0.307887
9                 Children     0.364654
10                    Pets    -0.269755

### Interpreting the coefficients

In [46]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [47]:
summary_table

Feature Name  Coefficient  Odds_ratio
0                Intercept    -1.690400    0.184446
1                 Reason_1     2.799721   16.440052
2                 Reason_2     0.912816    2.491329
3                 Reason_3     3.091301   22.005693
4                 Reason_4     0.853543    2.347952
5              Month Value     0.164193    1.178442
6   Transportation Expense     0.601323    1.824531
7                      Age    -0.167107    0.846109
8          Body Mass Index     0.307887    1.360547
9                 Children     0.364654    1.440016
10                    Pets    -0.269755    0.763566

In [48]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     3.091301   22.005693
1                 Reason_1     2.799721   16.440052
2                 Reason_2     0.912816    2.491329
4                 Reason_4     0.853543    2.347952
6   Transportation Expense     0.601323    1.824531
9                 Children     0.364654    1.440016
8          Body Mass Index     0.307887    1.360547
5              Month Value     0.164193    1.178442
7                      Age    -0.167107    0.846109
10                    Pets    -0.269755    0.763566
0                Intercept    -1.690400    0.184446

### Testing the model

In [49]:
reg.score(x_test, y_test)

0.75

In [50]:
predicted_proba = reg.predict_proba(x_test)

In [51]:
predicted_proba

array([[0.71535644, 0.28464356],
       [0.59611106, 0.40388894],
       [0.42786716, 0.57213284],
       [0.78525761, 0.21474239],
       [0.08646021, 0.91353979],
       [0.34307868, 0.65692132],
       [0.30626419, 0.69373581],
       [0.13292048, 0.86707952],
       [0.79454869, 0.20545131],
       [0.75195344, 0.24804656],
       [0.49729002, 0.50270998],
       [0.23009911, 0.76990089],
       [0.07525837, 0.92474163],
       [0.69219916, 0.30780084],
       [0.32557891, 0.67442109],
       [0.51294688, 0.48705312],
       [0.55565675, 0.44434325],
       [0.54405415, 0.45594585],
       [0.41510234, 0.58489766],
       [0.05495918, 0.94504082],
       [0.70760457, 0.29239543],
       [0.78525761, 0.21474239],
       [0.43043886, 0.56956114],
       [0.43043886, 0.56956114],
       [0.2638936 , 0.7361064 ],
       [0.75364944, 0.24635056],
       [0.5196258 , 0.4803742 ],
       [0.84218417, 0.15781583],
       [0.21144877, 0.78855123],
       [0.78525761, 0.21474239],
       [0.

In [52]:
predicted_proba.shape

(140, 2)

In [53]:
predicted_proba[:,1]

array([0.28464356, 0.40388894, 0.57213284, 0.21474239, 0.91353979,
       0.65692132, 0.69373581, 0.86707952, 0.20545131, 0.24804656,
       0.50270998, 0.76990089, 0.92474163, 0.30780084, 0.67442109,
       0.48705312, 0.44434325, 0.45594585, 0.58489766, 0.94504082,
       0.29239543, 0.21474239, 0.56956114, 0.56956114, 0.7361064 ,
       0.24635056, 0.4803742 , 0.15781583, 0.78855123, 0.21474239,
       0.35966883, 0.66538147, 0.67773056, 0.52612554, 0.21474239,
       0.53446841, 0.21320954, 0.72236056, 0.41038399, 0.60143923,
       0.20694305, 0.47416744, 0.22935989, 0.39124597, 0.83014621,
       0.54899527, 0.68100144, 0.28464356, 0.20643418, 0.19935507,
       0.60162564, 0.35957904, 0.65692132, 0.25630121, 0.82590665,
       0.42665066, 0.87732358, 0.22536372, 0.34147178, 0.35209031,
       0.72598082, 0.64627967, 0.28771101, 0.77906434, 0.20376492,
       0.2659438 , 0.08036408, 0.21320954, 0.70913836, 0.34912081,
       0.21320954, 0.27263632, 0.90751086, 0.46804741, 0.60333

### Save the model

In [54]:
import pickle

In [55]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [56]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)